"""Added contacts column to users table

Revision ID: 97340e8473c9
Revises: bb3be8755669
Create Date: 2025-05-30 18:53:51.842143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97340e8473c9'
down_revision: Union[str, None] = 'bb3be8755669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###
